### ISSUE TITLE
게임을 오래 플레이하면 프레임 저하가 발생합니다.

### ISSUE THREAD

**Issue by Yoon-SeokJin2** [seokjin1013/wizard-of-the-forest#2]
원래 60프레임이었는데 서서히 떨어지기 시작하더니 34프레임까지 떨어졌습니다.
계속하면 더 떨어질 것 같습니다.
![asdf](https://github.com/seokjin1013/wizard-of-the-forest-3/assets/130483717/80962a0c-240d-4072-b7ed-1276fa6eba43)

**Comment by seokjin1013** [comment]
혹시 맵에 나무가 얼마나 있나요? 현재는 특별한 충돌처리 알고리즘을 사용하지 않아 총알과 나무의 충돌체크가 1대1로 일어나기 때문에 나무가 많을 경우 프레임이 떨어질 수 있습니다. 추후에 수정할 예정입니다.

**Comment by Yoon-SeokJin2** [comment]
현재 맵에 나무는 하나도 없는 상태입니다. 그래도 총알을 오랫동안 쏘고 있으면 프레임이 점점 떨어집니다.

**Comment by seokjin1013** [comment]
한 번 살펴보겠습니다.
